#!/usr/bin/env python
# _*_ coding:utf-8 _*_
import pandas as pd
import numpy as np


def quarter_volume():
    data = pd.read_csv('apple.csv', header=0)
    data.index = pd.to_datetime(data.Date)
    vols = data.resample('Q').sum().Volume
    second_volume = vols[np.argpartition(vols, -2)[-2]]
    ''' np.argpartition 的使用'''
    '''
    补充代码：
    1. 使用 Pandas 选择数据
    2. 转换为时间序列
    3. 按季度重采样并排序
    '''

    return second_volume
if __name__ == '__main__':
    quarter_volume()

